# Display
name: GSlotMachine
description: 'Gamble easily with this nice machine'
author: GuillaumeVDN
website: www.guillaumevdn.com
# Techy
version: ${project.version}
api-version: ${api.version}
main: com.guillaumevdn.gslotmachine.GSlotMachine
depend: [GCore,Vault]
# Commands
commands:
  machine:
    aliases: [gslotmachine,slotmachine]
permissions:
  gslotmachine.admin:
    default: op
