#----------------------------------------------------------------------------------------------------
# Configuration file for GSlotMachine
#----------------------------------------------------------------------------------------------------

# Data management
data:
  # Back end (JSON, MYSQL) (default JSON)
  # If you enable MySQL here, you should definitely enable it for GCore as well
  backend: JSON
  # Synchronization delay (in seconds) (disabled with -1, by default)
  # If this is enabled, the plugin will check the stored data (json/mysql), and if there's new/different data, cached data will be overriden here
  sync_delay: -1
  # MySQL identifiers (if backend is MYSQL)
#  mysql:
#    host: mysql.myserver.com
#    name: mydatabase
#    user: username
#    pass: pwd

# Machines types
types:
  gold:
    cost: 100.0
    animation_sound: WOOD_CLICK
    win_sound: LEVEL_UP
    lose_sound: ANVIL_BREAK
    prizes:
      1:
        type: GOLD_INGOT
        amount: 16
        chance: 30
      2:
        type: DIAMOND
        amount: 1
        chance: 10
      3:
        type: QUARTZ
        amount: 32
        chance: 10
      4:
        type: COBBLESTONE
        amount: 64
        chance: 20
      5:
        type: APPLE
        amount: 16
        chance: 10
      6:
        type: DEAD_BUSH
        amount: 16
        chance: 10
      7:
        type: BONE
        amount: 16
        chance: 10
