#----------------------------------------------------------------------------------------------------
# Configuration file for GSlotMachine
#----------------------------------------------------------------------------------------------------

# Data management
data:
  # Back end (JSON, MYSQL) (default JSON)
  # If you enable MySQL here, you should definitely enable it for GCore as well
  backend: JSON
  # Synchronization delay (in seconds) (disabled with -1, by default)
  # If this is enabled, the plugin will check the stored data (json/mysql), and if there's new/different data, cached data will be overriden here
  sync_delay: -1
  # MySQL identifiers (if backend is MYSQL)
#  mysql:
#    host: mysql.myserver.com
#    name: mydatabase
#    user: username
#    pass: pwd

# Machines types
types:
  gold:
    cost: 100.0
    animation_sound: BLOCK_WOODEN_BUTTON_CLICK_ON
    win_sound: ENTITY_PLAYER_LEVELUP
    lose_sound: BLOCK_ANVIL_BREAK
    prizes:
      1:
        type: GOLD_INGOT
        amount: 16
        chance: 30
        give_item: true
        commands:
          - 'broadcast &a{player} won 16 gold ingot in a slot machine !'
      2:
        type: DIAMOND
        amount: 1
        chance: 10
        give_item: true
        commands:
          - 'broadcast &a{player} won 1 diamond in a slot machine !'
      3:
        type: QUARTZ
        amount: 32
        chance: 10
        give_item: true
        commands:
          - 'broadcast &a{player} won 32 quartz in a slot machine !'
      4:
        type: COBBLESTONE
        amount: 64
        chance: 20
        give_item: true
        commands:
          - 'broadcast &a{player} won 64 cobblestones in a slot machine !'
      5:
        type: APPLE
        amount: 16
        chance: 10
        give_item: true
        commands:
          - 'broadcast &a{player} won 16 apples in a slot machine !'
      6:
        type: DEAD_BUSH
        amount: 16
        chance: 10
        give_item: true
        commands:
          - 'broadcast &a{player} won 16 dead bushes in a slot machine !'
      7:
        type: BONE
        amount: 16
        chance: 10
        give_item: true
        commands:
          - 'broadcast &a{player} won 16 bones in a slot machine !'
